Home work #3 v1
tsoy-petr/A_F_homework pull request #3
Opened 2020-11-28 12:35 UTC by tsoy-petr

2020-11-30 11:29 UTC, konstzv requested changes
Исправь замечания и запуш в эту же ветку исправления

2020-11-30 11:29 UTC, konstzv commented on app/src/main/java/com/android/hootor/academy/fundamentals/homework/MainActivity.kt
> +import com.google.android.material.card.MaterialCardView
Лишний импорт - всегда удаляй ненужные импорты, через code -> optimize import например

2020-11-30 11:29 UTC, konstzv commented on app/src/main/java/com/android/hootor/academy/fundamentals/homework/FragmentMoviesList.kt
> +        savedInstanceState: Bundle?
форматирование -> лучше все аргументы с новой строки если в одну не умещаются - можно запутаться когда то два аргумента то один

2020-11-30 11:29 UTC, konstzv commented on app/src/main/res/layout/fragment_movies_list.xml
> +    android:background="#191926">
цвета вынеси в colors.xml и далее также

2020-11-30 11:29 UTC, konstzv commented on app/src/main/res/layout/fragment_movies_list.xml
> +
у тебя между тэгами то 2 то 1 строка - сделай 1 - придерживайся одного стиля

2020-11-30 11:29 UTC, konstzv commented on app/src/main/res/layout/fragment_movies_list.xml
> +        android:id="@+id/imageView2"
нормально называй вьюшку - чтобы было понятно что это
используй одинаковое наименование - у тебя снизу iv_.... а тут imageView -
и далее по файлу тоже именования поправь

2020-11-30 11:29 UTC, konstzv commented on app/src/main/res/layout/fragment_movies_list.xml
> +        android:text="Movies list" />
весь текст в strings.xml и далее также

2020-11-30 11:29 UTC, konstzv commented on app/src/main/res/layout/fragment_movies_list.xml
> +        android:layout_marginTop="55dp"
размеры лучше задавать кратные 2 а лучше 4 - при переводе в пиксели могут получится дробные значения и пиксель потеряется - будет не так точно

2020-11-30 11:29 UTC, konstzv commented on app/src/main/res/layout/fragment_movies_list.xml
> +                app:shapeAppearanceOverlay="@style/ShapeAppearanceOverlay.App.CornerSize14dp"
почему тут 14dp в  названии стиля - а внутри 12dp

2020-11-30 11:29 UTC, konstzv commented on app/src/main/res/layout/fragment_movies_list.xml
> +                android:layout_height="246dp"
ты у карточки точный размер уже задал - тут сделай просто марджины от краев - точные размеры уже не надо

2020-11-30 11:29 UTC, konstzv commented on app/src/main/res/layout/fragment_movies_list.xml
> +                android:layout_height="24dp"
wrap_content -  если нужны отступы внутри то делай padding. Если шрифт указан в sp - его можно увеличить в настройках телефона и тогда у тебя шрифт не уместится в 24 на 24 dp

2020-11-30 11:29 UTC, konstzv commented on app/src/main/res/layout/fragment_movies_list.xml
> +                app:layout_constraintTop_toTopOf="@+id/ratingBar"
нужен констрейнт end - также подумай что текст может не уместиться - тогда нужно ellipsize

2020-11-30 11:29 UTC, konstzv commented on app/src/main/java/com/android/hootor/academy/fundamentals/homework/FragmentMoviesList.kt
> +            requireActivity().supportFragmentManager.beginTransaction()
не нужно напрямую обращатсья к актвити - определи у фрамента интерфейс on....Clicked и пусть активити его имплементит - посмотри пример в лекции

2020-11-30 11:29 UTC, konstzv commented on app/src/main/java/com/android/hootor/academy/fundamentals/homework/FragmentMoviesDetails.kt
> +            requireActivity().supportFragmentManager.popBackStack()
тоже самое - обращайся к активти как к интерфейсу

2020-11-30 11:29 UTC, konstzv commented on app/src/main/java/com/android/hootor/academy/fundamentals/homework/FragmentMoviesDetails.kt
> +        inflater: LayoutInflater, container: ViewGroup?,
форматирование - в две строки

2020-11-30 11:29 UTC, konstzv commented on app/src/main/java/com/android/hootor/academy/fundamentals/homework/FragmentMoviesList.kt
> +        // Inflate the layout for this fragment
комментарии не оставляй в коде - код должен сам за себя говорить

2020-11-30 11:29 UTC, konstzv commented on app/src/main/java/com/android/hootor/academy/fundamentals/homework/FragmentMoviesList.kt
> +                    FragmentMoviesDetails()
Fragment даже без аргументов лучше создавать через статический метод createInstance - было в лекции. В будущем как появятся аргументы - уже все будет готово

2020-11-30 11:29 UTC, konstzv commented on app/src/main/java/com/android/hootor/academy/fundamentals/homework/FragmentMoviesList.kt
> +
одна строка лишняя

2020-11-30 11:29 UTC, konstzv commented on app/src/main/res/layout/fragment_movies_details.xml
> +            app:layout_constraintHorizontal_bias="0.0"
зачем этот атрибут?

2020-11-30 11:29 UTC, konstzv commented on app/src/main/res/values/strings.xml
> +    <!-- TODO: Remove or change this placeholder text -->
удали комментарий

2020-11-30 11:29 UTC, konstzv commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
неиспользуемые ресусры удали

2020-11-30 11:33 UTC, konstzv commented on app/src/main/res/layout/fragment_movies_list.xml
> +    <ImageView
или нормальный android:contentDescription делай или заглушай предупреждения через tools:ignore="ContentDescription" или в build.gradle в androd{ lintOptions {disable '...}

2020-11-30 12:01 UTC, tsoy-petr commented on app/src/main/java/com/android/hootor/academy/fundamentals/homework/MainActivity.kt
> +import com.google.android.material.card.MaterialCardView
import androidx.appcompat.app.AppCompatActivity если его убрать, то AS ругается

2020-11-30 12:14 UTC, tsoy-petr commented on app/src/main/res/layout/fragment_movies_list.xml
> +        android:text="Movies list" />
Может весь текст сделать через tools?

2020-11-30 12:16 UTC, tsoy-petr commented on app/src/main/res/layout/fragment_movies_list.xml
> +        android:text="Movies list" />
Просто на предыдущих занятиях лектор говорил, что можно хардкодить.

2020-11-30 12:16 UTC, tsoy-petr commented on app/src/main/res/layout/fragment_movies_list.xml
> +        android:text="Movies list" />
Я про ресурсы...

2020-12-02 08:58 UTC, konstzv commented on app/src/main/res/layout/fragment_movies_list.xml
> +        android:text="Movies list" />
Не надо хардкодить, через tools будет видно только в студии

2020-12-02 08:58 UTC, konstzv commented on app/src/main/java/com/android/hootor/academy/fundamentals/homework/MainActivity.kt
> +import com.google.android.material.card.MaterialCardView
я про MaterialCardView

2020-12-07 09:02 UTC, konstzv commented on app/src/main/java/com/android/hootor/academy/fundamentals/homework/FragmentMoviesList.kt
> +            requireActivity().supportFragmentManager.beginTransaction()
ты зачем-то накидал кучу левых зависимостей и ненжного кода, а это не поправил

2020-12-08 13:22 UTC, tsoy-petr commented on app/src/main/res/layout/fragment_movies_list.xml
> +                android:layout_height="24dp"
Не понятно, что делать если будет 3+, то как padding поможет?

2020-12-09 11:06 UTC, konstzv commented on app/src/main/java/com/android/hootor/academy/fundamentals/homework/FragmentMoviesList.kt
> +        fun onClickData(): Unit
Unit лишнее

2020-12-09 11:06 UTC, konstzv commented on app/src/main/java/com/android/hootor/academy/fundamentals/homework/FragmentMoviesList.kt
> +        fun onClickData(): Unit
onDataClick или onDataClicked

2020-12-09 11:08 UTC, konstzv commented on app/src/main/res/values/strings.xml
> +    <string name="debug_13_plus">13+</string>
заачем debug фраза
пока это единственные значение, не дебаг нет

2020-12-09 11:10 UTC, konstzv commented on app/src/main/java/com/android/hootor/academy/fundamentals/homework/FragmentMoviesList.kt
> +            throw RuntimeException("$context must implement FragmentMoviesList.OnClickListener")
эт можно, но мне кажется перебор - мы можем позволить использовать фрагмент как просто список

2020-12-09 11:11 UTC, konstzv approved these changes

2020-12-09 13:26 UTC, konstzv commented on app/src/main/java/com/android/hootor/academy/fundamentals/homework/FragmentMoviesList.kt
>          if (context is MainActivity) {
тут к интерфейсу приводи

2020-12-09 14:06 UTC, konstzv approved these changes

2020-12-09 23:42 UTC, merged